# docker-bake.hcl — the whole image family (ADR-0008, ADR-0013).
#   docker buildx bake -f resources.hcl -f docker-bake.hcl tools        # local platform
#   PLATFORMS=linux/amd64,linux/arm64 ATTEST=true TAG=2026-09-06 ... --push  # multi-arch
# resources.hcl is generated by `make hcl` from resources.yaml (image digests).

variable "REGISTRY"  { default = "harbor.cyverse.org/vice" }
variable "TAG"       { default = "dev" }
variable "PLATFORMS" { default = "linux/arm64" }          # comma-separated; e.g. "linux/amd64,linux/arm64"
variable "GIT_SHA"   { default = "unknown" }
variable "SOURCE_DATE_EPOCH" { default = "0" }
variable "PUSH_BY_DIGEST"    { default = "false" }
variable "ATTEST"            { default = "false" }   # provenance+SBOM need the docker-container driver or a push

function "cache_from" {
  params = [name]
  result = ["type=registry,ref=${REGISTRY}/mesa-cache:${name}"]
}
function "cache_to" {
  params = [name]
  result = ["type=registry,ref=${REGISTRY}/mesa-cache:${name},mode=max"]
}

group "default" { targets = ["tools"] }
group "all"     { targets = ["tools", "cli", "jupyterlab", "rstudio", "vscode", "kasm", "agent-runner"] }
group "test"    { targets = ["tools-test"] }

target "_common" {
  context    = "."
  platforms  = split(",", PLATFORMS)
  attest     = ATTEST == "true" ? ["type=provenance,mode=max", "type=sbom"] : []
  args       = { SOURCE_DATE_EPOCH = SOURCE_DATE_EPOCH }
  labels = {
    "org.opencontainers.image.source"   = "https://github.com/idss-mesa/mesa-sandbox"
    "org.opencontainers.image.revision" = GIT_SHA
    "org.opencontainers.image.vendor"   = "NSF MESA / University of New Mexico CARC / CyVerse"
    "org.opencontainers.image.licenses" = "MIT"
  }
  # pinned base/builder images from resources.hcl
  contexts = {
    ubuntu = "docker-image://${IMG_UBUNTU_NOBLE}"
    golang = "docker-image://${IMG_GOLANG}"
    uv     = "docker-image://${IMG_UV}"
  }
  output     = PUSH_BY_DIGEST == "true" ? ["type=image,push-by-digest=true,name-canonical=true,push=true,rewrite-timestamp=true"] : ["type=docker"]
}

target "tools" {
  inherits   = ["_common"]
  dockerfile = "images/tools/Dockerfile"
  target     = "tools"
  tags       = ["${REGISTRY}/mesa-tools:${TAG}"]
  cache-from = cache_from("tools")
  cache-to   = cache_to("tools")
}

target "tools-test" {
  inherits   = ["_common"]
  dockerfile = "images/tools/Dockerfile"
  target     = "tools-test"
  output     = ["type=cacheonly"]
}

# App overlays (Phase 2): each is FROM a pinned base and COPY --from=tools.
target "cli" {
  inherits   = ["_common"]
  dockerfile = "images/cli/Dockerfile"
  contexts   = { base = "docker-image://${IMG_JUPYTER_MINIMAL}", tools = "target:tools" }
  tags       = ["${REGISTRY}/mesa-cli:${TAG}"]
  cache-from = cache_from("cli")
  cache-to   = cache_to("cli")
}
target "jupyterlab" {
  inherits   = ["_common"]
  dockerfile = "images/jupyterlab/Dockerfile"
  contexts   = { base = "docker-image://${IMG_JUPYTER_DATASCIENCE}", tools = "target:tools" }
  tags       = ["${REGISTRY}/mesa-jupyterlab:${TAG}"]
  cache-from = cache_from("jupyterlab")
  cache-to   = cache_to("jupyterlab")
}
target "rstudio" {
  inherits   = ["_common"]
  dockerfile = "images/rstudio/Dockerfile"
  contexts   = { base = "docker-image://${IMG_ROCKER_GEOSPATIAL}", tools = "target:tools" }
  tags       = ["${REGISTRY}/mesa-rstudio:${TAG}"]
  cache-from = cache_from("rstudio")
  cache-to   = cache_to("rstudio")
}
target "vscode" {
  inherits   = ["_common"]
  dockerfile = "images/vscode/Dockerfile"
  contexts   = { base = "docker-image://${IMG_CODE_SERVER}", tools = "target:tools" }
  tags       = ["${REGISTRY}/mesa-vscode:${TAG}"]
  cache-from = cache_from("vscode")
  cache-to   = cache_to("vscode")
}
target "kasm" {
  inherits   = ["_common"]
  dockerfile = "images/kasm/Dockerfile"
  contexts   = { base = "docker-image://${IMG_KASM_AI_DEV}", tools = "target:tools" }
  tags       = ["${REGISTRY}/mesa-kasm:${TAG}"]
  cache-from = cache_from("kasm")
  cache-to   = cache_to("kasm")
}
target "agent-runner" {
  inherits   = ["_common"]
  dockerfile = "images/agent-runner/Dockerfile"
  contexts   = { base = "docker-image://${IMG_UBUNTU_NOBLE}", tools = "target:tools" }
  tags       = ["${REGISTRY}/mesa-agent-runner:${TAG}"]
  cache-from = cache_from("agent-runner")
  cache-to   = cache_to("agent-runner")
}
