# generated by scripts/resources.py hcl from resources.yaml — do not edit
variable "IMG_UBUNTU_NOBLE" { default = "docker.io/library/ubuntu:24.04@sha256:33ceb71981b602c1a7443a53469e4dba065f7503eab3078a2d7a57a2ab987517" }
variable "IMG_JUPYTER_MINIMAL" { default = "quay.io/jupyter/minimal-notebook:2026-09-01@sha256:aebcf531fc77f3341568f5e37de7eb392ae48f1ae5ce9bc9cf779bd602548d17" }
variable "IMG_JUPYTER_DATASCIENCE" { default = "quay.io/jupyter/datascience-notebook:2026-09-01@sha256:c2bb6cf9516cf786ce0ea154e5f7093544aaaa57d5cafd1f9aa9f8c3d0942e28" }
variable "IMG_ROCKER_GEOSPATIAL" { default = "ghcr.io/rocker-org/geospatial:4.6.1@sha256:4cee92a576e26c31546860eb252290f8f259e8236d49600d6bee695dfb96cae5" }
variable "IMG_CODE_SERVER" { default = "ghcr.io/coder/code-server:4.135.0@sha256:ccd326184d71efc5ebb94155eda7bb30153902342a35dbc8525450d81aa55012" }
variable "IMG_KASM_AI_DEV" { default = "docker.io/kasmweb/ubuntu-jammy-desktop-ai-dev:1.19.0@sha256:af7b6c40c8fbca6097d40268feaf5ddeca1311663388eff8628b3ec8900793d1" }
variable "IMG_KASM_NVIDIA_PYTORCH" { default = "docker.io/kasmweb/ubuntu-noble-nvidia-pytorch:1.19.0@sha256:442976c40eecd41c7f5ae8c942aaa992e18db582f81d2ed324b9fa7292bee7e2" }
variable "IMG_GOLANG" { default = "docker.io/library/golang:1.25-bookworm@sha256:3b4a11519ad929d1e1d261a12cff056f0c85b735253d7d861346b9c6f8b36437" }
variable "IMG_UV" { default = "ghcr.io/astral-sh/uv:0.9.4-python3.13-bookworm-slim@sha256:661ae5d98b045922b10684e22214cbeabe38d5bcdc900025d4c3e8174b304511" }
