#!/usr/bin/env python3
"""resources.py — lock, verify and export the artifacts declared in resources.yaml.

Subcommands
  lock      download every artifact (streaming), compute sha256, cross-check any
            upstream checksum file, and write the digests back into resources.yaml
  export    write resources.lock (tab-separated: name, platform, url, sha256,
            filename, version) consumed by images/tools/fetch.sh inside builds
  check     exit non-zero if any artifact lacks a sha256 or the lock is stale
  images    print the pinned base-image references (for docker-bake.hcl)

Design (ADR-0011): the YAML is the only place a URL may appear; Dockerfiles use
fetch.sh, which refuses to download anything that is not in resources.lock or
whose sha256 does not match.
"""
from __future__ import annotations
import argparse, hashlib, json, re, subprocess, sys, urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
YAML = ROOT / "resources.yaml"
LOCK = ROOT / "resources.lock"
PLATFORMS = ("linux/amd64", "linux/arm64")

def load():
    import yaml  # PyYAML (make venv: python3 -m venv .venv && .venv/bin/pip install pyyaml)
    return yaml.safe_load(YAML.read_text())

def dump(doc):
    import yaml
    class D(yaml.SafeDumper):
        def increase_indent(self, flow=False, indentless=False):
            return super().increase_indent(flow, False)
    YAML.write_text(yaml.dump(doc, Dumper=D, sort_keys=False, width=200, allow_unicode=True))

def sha256_url(url: str) -> tuple[str, int]:
    h = hashlib.sha256(); n = 0
    req = urllib.request.Request(url, headers={"User-Agent": "mesa-sandbox-resources/1"})
    with urllib.request.urlopen(req, timeout=120) as r:
        while True:
            b = r.read(1 << 20)
            if not b: break
            h.update(b); n += len(b)
    return h.hexdigest(), n

def upstream_digest(check: dict, filename: str) -> str | None:
    """Fetch an upstream checksum file and return the digest for filename."""
    url = check["url"]; algo = check.get("algo", "sha256")
    with urllib.request.urlopen(url, timeout=60) as r:
        text = r.read().decode()
    for line in text.splitlines():
        parts = line.split()
        if len(parts) >= 2 and parts[-1].lstrip("*") .endswith(filename):
            return parts[0].lower()
        if len(parts) == 1 and check.get("bare"):  # file holds only the digest
            return parts[0].lower()
    return None

def cmd_lock(args):
    doc = load(); changed = 0
    for res in doc["resources"]:
        if res.get("kind") not in ("archive", "binary", "source"): continue
        for plat, art in res.get("artifacts", {}).items():
            if art.get("sha256") and not args.force: continue
            print(f"[lock] {res['name']} {plat} {art['url']}", flush=True)
            digest, size = sha256_url(art["url"])
            art["sha256"] = digest; art["size"] = size
            chk = art.get("upstream_checksum") or res.get("upstream_checksum")
            if chk:
                fname = art.get("filename") or art["url"].rsplit("/", 1)[-1]
                c = dict(chk); c["url"] = c["url"].format(filename=fname, platform=plat)
                up = upstream_digest(c, fname)
                if c.get("algo", "sha256") == "sha256":
                    if up is None: print(f"  ! upstream checksum file has no entry for {fname}")
                    elif up != digest: sys.exit(f"  !! MISMATCH for {res['name']} {plat}: upstream {up} != computed {digest}")
                    else: print(f"  ok upstream sha256 matches")
                elif c.get("algo") == "sha512-inline":
                    print(f"  (upstream publishes sha512 inline; recorded in YAML as sha512_upstream)")
            changed += 1
    if changed: dump(doc)
    print(f"locked {changed} artifact(s)")

def cmd_export(args):
    doc = load(); rows = []
    for res in doc["resources"]:
        for plat, art in res.get("artifacts", {}).items():
            if not art.get("sha256"): sys.exit(f"missing sha256: {res['name']} {plat} (run lock)")
            fname = art.get("filename") or art["url"].rsplit("/", 1)[-1]
            rows.append("\t".join([res["name"], plat, art["url"], art["sha256"], fname, str(res.get("version", ""))]))
    LOCK.write_text("# generated by scripts/resources.py export — do not edit\n" + "\n".join(rows) + "\n")
    print(f"wrote {LOCK} ({len(rows)} rows)")

def cmd_check(args):
    doc = load(); bad = [r["name"] for r in doc["resources"] for p, a in r.get("artifacts", {}).items() if not a.get("sha256")]
    if bad: sys.exit(f"unlocked artifacts: {sorted(set(bad))}")
    cur = LOCK.read_text() if LOCK.exists() else ""
    hcl = ROOT / "resources.hcl"; curh = hcl.read_text() if hcl.exists() else ""
    cmd_export(argparse.Namespace()); cmd_hcl(argparse.Namespace())
    if LOCK.read_text() != cur or hcl.read_text() != curh: sys.exit("resources.lock/resources.hcl were stale; regenerated — commit them")
    print("ok")

def cmd_hcl(args):
    """Write resources.hcl: one bake variable per pinned image (IMG_<NAME>)."""
    doc = load(); out = ["# generated by scripts/resources.py hcl from resources.yaml — do not edit"]
    for name, img in doc["images"].items():
        var = "IMG_" + re.sub(r"[^A-Za-z0-9]", "_", name).upper()
        out.append(f'variable "{var}" {{ default = "{img["ref"]}@{img["digest"]}" }}')
    (ROOT / "resources.hcl").write_text("\n".join(out) + "\n")
    print(f"wrote resources.hcl ({len(doc['images'])} images)")

def cmd_images(args):
    doc = load()
    for name, img in doc["images"].items():
        print(f"{name}\t{img['ref']}@{img['digest']}\t{img.get('platforms','')}")

if __name__ == "__main__":
    p = argparse.ArgumentParser(); s = p.add_subparsers(dest="cmd", required=True)
    l = s.add_parser("lock"); l.add_argument("--force", action="store_true"); l.set_defaults(f=cmd_lock)
    s.add_parser("export").set_defaults(f=cmd_export)
    s.add_parser("check").set_defaults(f=cmd_check)
    s.add_parser("hcl").set_defaults(f=cmd_hcl)
    s.add_parser("images").set_defaults(f=cmd_images)
    a = p.parse_args(); a.f(a)
